include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true          # Warn if you use print() (use logger instead)
    prefer_const_constructors: true   # Force using const where possible
    prefer_single_quotes: true # Enforce single quotes for strings
    always_declare_return_types: true # Enforce return types instead of `dynamic`
    avoid_unnecessary_containers: true # Warn if a Container is redundant
    unnecessary_null_checks: true     # Catch redundant null checks
    avoid_init_to_null: true
    use_key_in_widget_constructors: true
